---
- name: Configure firewall for Apache
  hosts: all
  become: yes
  tasks:
    - name: Allow HTTP (port 80) through UFW
      ansible.builtin.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow HTTPS (port 443) through UFW
      ansible.builtin.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Reload UFW to apply changes
      ansible.builtin.command: ufw reload
      when: ansible_facts['os_family'] == 'Debian'  # Optional: limit to UFW-supported systems
